In [1]:
import pandas as pd
import numpy as np
import akshare as ak
import pandas_ta  as ta

from lutils.stock import LTdxHq

In [2]:
stock_zcfz_em_df = ak.stock_zcfz_em() # 总资产， 资产负债

 10%|████▎                                      | 1/10 [00:00<00:03,  2.52it/s]D:\Software\Python\Python39\lib\site-packages\akshare\stock_feature\stock_report_em.py:50: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  big_df = pd.concat([big_df, temp_df], ignore_index=True)

In [3]:
stock_zcfz_em_df

,序号,股票代码,股票简称,资产-货币资金,资产-应收账款,资产-存货,资产-总资产,资产-总资产同比,负债-应付账款,负债-预收账款,负债-总负债,负债-总负债同比,资产负债率,股东权益合计,公告日期
0,1,301206,三元生物,5.015787e+08,1.387858e+08,1.104237e+08,5.120094e+09,459.528231,8.257242e+07,NaN,4.651859e+08,NaN,9.085495,4.654908e+09,2024-02-05
1,2,002570,贝因美,7.620811e+08,7.380092e+08,3.955900e+08,4.112136e+09,-0.718538,2.680464e+08,NaN,2.257925e+09,-13.763043,54.908798,1.854212e+09,2024-01-31
2,3,688260,昀冢科技,6.009653e+07,1.883036e+08,1.024070e+08,1.000385e+09,7.318599,1.115307e+08,NaN,4.981502e+08,13.616560,49.795861,5.022345e+08,2024-01-18
3,4,300008,天海防务,2.645188e+08,1.747129e+08,2.296047e+08,2.808647e+09,33.841307,2.372219e+08,NaN,1.128505e+09,157.421725,40.179661,1.680142e+09,2024-01-17
4,5,603718,海利生物,6.207494e+07,1.115710e+08,1.375633e+08,1.818882e+09,1.172012,2.576611e+07,NaN,8.258160e+08,-1.010881,45.402404,9.930657e+08,2023-10-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4778,4779,000921,海信家电,6.743127e+09,9.144377e+09,8.040829e+09,5.499510e+10,22.230338,1.135781e+10,NaN,3.942916e+10,30.284660,71.695759,1.556595e+10,2022-04-12
4779,4780,000838,财信发展,1.502056e+09,1.394220e+08,9.071772e+09,1.369390e+10,-24.981781,1.833591e+09,37082299.13,1.178645e+10,-23.468821,86.070793,1.907452e+09,2022-04-12
4780,4781,600313,农发种业,6.534196e+08,2.499272e+08,4.663269e+08,3.384655e+09,5.444774,1.266408e+08,12320541.60,1.114699e+09,5.928760,32.933914,2.269956e+09,2022-04-08
4781,4782,600731,湖南海利,5.530404e+08,3.174709e+08,4.441485e+08,3.469732e+09,10.066273,3.458080e+08,10692347.10,1.575893e+09,3.668756,45.418289,1.893839e+09,2022-04-07
4782,4783,300692,中环环保,1.785091e+08,4.046044e+08,6.327379e+06,5.466756e+09,22.299683,4.782340e+08,NaN,3.190832e+09,33.532717,58.367935,2.275923e+09,2022-04-02

In [4]:
stock_zh_a_spot_em_df = ak.stock_zh_a_spot_em() # 市盈率

In [5]:
stock_zh_a_spot_em_df

,序号,代码,名称,最新价,涨跌幅,涨跌额,成交量,成交额,振幅,最高,...,量比,换手率,市盈率-动态,市净率,总市值,流通市值,涨速,5分钟涨跌,60日涨跌幅,年初至今涨跌幅
0,1,835438,N戈碧迦,25.25,152.50,15.25,320179.0,6.943739e+08,59.30,25.70,...,1390.15,56.09,33.50,4.07,3.490812e+09,1.441265e+09,1.00,0.28,292.08,292.08
1,2,300419,浩丰科技,7.12,20.07,1.19,542732.0,3.602531e+08,22.77,7.12,...,1.25,14.76,146.64,4.19,2.618407e+09,2.618407e+09,0.00,0.00,-0.84,20.68
2,3,300921,南凌科技,25.62,14.07,3.16,174354.0,4.408404e+08,22.93,26.95,...,3.84,13.24,162.85,4.17,3.378371e+09,3.373944e+09,0.16,0.23,1.83,4.23
3,4,300988,津荣天宇,19.59,13.90,2.39,129199.0,2.496295e+08,20.87,20.64,...,5.82,22.37,31.46,2.45,2.748425e+09,1.131303e+09,0.98,1.50,-11.72,-7.94
4,5,301161,唯万密封,18.88,13.87,2.30,61331.0,1.172973e+08,14.41,19.89,...,4.73,11.50,54.25,2.44,2.265600e+09,1.006833e+09,0.43,0.37,-4.50,-6.63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5598,5599,300133,华策影视,9.93,-10.22,-1.13,3021393.0,3.030278e+09,7.14,10.50,...,2.27,18.56,43.26,2.69,1.887766e+10,1.616873e+10,0.40,0.40,51.14,69.17
5599,5600,301306,西测测试,39.87,-10.24,-4.55,78081.0,3.178431e+08,7.32,42.64,...,2.11,19.88,-157.73,2.79,3.365028e+09,1.566094e+09,-0.33,-0.30,5.59,0.71
5600,5601,688070,纵横股份,48.83,-11.22,-6.17,31470.0,1.658879e+08,18.27,57.25,...,1.07,3.59,-71.87,7.00,4.276531e+09,4.276531e+09,1.71,0.56,48.28,42.40
5601,5602,301202,朗威股份,36.23,-11.31,-4.62,88341.0,3.257051e+08,9.01,39.40,...,0.94,25.91,85.27,4.05,4.941772e+09,1.235443e+09,-0.25,-0.33,12.20,12.76
5602,5603,688629,华丰科技,29.77,-11.64,-3.92,89444.0,2.752103e+08,8.85,32.43,...,0.91,12.93,189.01,9.13,1.372376e+10,2.058560e+09,0.03,-0.17,27.60,35.94

In [6]:
stock_zh_a_spot_em_df[stock_zh_a_spot_em_df['代码'] == '301119']

,序号,代码,名称,最新价,涨跌幅,涨跌额,成交量,成交额,振幅,最高,...,量比,换手率,市盈率-动态,市净率,总市值,流通市值,涨速,5分钟涨跌,60日涨跌幅,年初至今涨跌幅
1267,1268,301119,正强股份,22.13,0.96,0.21,3750.0,8239640.0,2.24,22.24,...,1.6,1.37,22.79,2.47,2.301520e+09,604149000.0,0.45,0.32,-15.6,-14.49

In [7]:
stock_zh_a_spot_em_df.columns

Index(['序号', '代码', '名称', '最新价', '涨跌幅', '涨跌额', '成交量', '成交额', '振幅', '最高', '最低',
       '今开', '昨收', '量比', '换手率', '市盈率-动态', '市净率', '总市值', '流通市值', '涨速', '5分钟涨跌',
       '60日涨跌幅', '年初至今涨跌幅'],
      dtype='object')

### 股票代码

In [8]:
stock_info_sh_name_code_df = ak.stock_info_sh_name_code(symbol="主板A股")

In [9]:
stock_info_sh_name_code_df = stock_info_sh_name_code_df[~stock_info_sh_name_code_df['证券简称'].str.startswith('ST') & ~stock_info_sh_name_code_df['证券简称'].str.startswith('*ST')]

In [10]:
stock_info_sh_name_code_df

        证券代码  证券简称                公司全称        上市日期
0     600000  浦发银行      上海浦东发展银行股份有限公司  1999-11-10
1     600004  白云机场      广州白云国际机场股份有限公司  2003-04-28
2     600006  东风汽车          东风汽车股份有限公司  1999-07-27
3     600007  中国国贸      中国国际贸易中心股份有限公司  1999-03-12
4     600008  首创环保    北京首创生态环保集团股份有限公司  2000-04-27
...      ...   ...                 ...         ...
1693  605580  恒盛能源          恒盛能源股份有限公司  2021-08-19
1694  605588  冠石科技        南京冠石科技股份有限公司  2021-08-12
1695  605589  圣泉集团        济南圣泉集团股份有限公司  2021-08-10
1696  605598  上海港湾  上海港湾基础建设(集团)股份有限公司  2021-09-17
1697  605599  菜百股份       北京菜市口百货股份有限公司  2021-09-09

[1658 rows x 4 columns]

In [11]:
stock_info_sz_name_code_df = ak.stock_info_sz_name_code(symbol="A股列表")

In [12]:
stock_info_sz_name_code_df = stock_info_sz_name_code_df[(stock_info_sz_name_code_df['板块'] == '主板') | (stock_info_sz_name_code_df['板块'] == '创业板')]
stock_info_sz_name_code_df = stock_info_sz_name_code_df[~stock_info_sz_name_code_df['A股简称'].str.startswith('ST') & ~stock_info_sz_name_code_df['A股简称'].str.startswith('*ST')]

In [13]:
stock_info_sz_name_code_df

       板块    A股代码   A股简称      A股上市日期           A股总股本          A股流通股本    所属行业
0      主板  000001   平安银行  1991-04-03  19,405,918,198  19,405,513,424   J 金融业
1      主板  000002  万  科Ａ  1991-01-29   9,724,196,533   9,716,935,865   K 房地产
2      主板  000004   国华网安  1990-12-01     132,380,282     126,288,093  I 信息技术
4      主板  000006   深振业Ａ  1992-04-27   1,349,995,046   1,349,987,396   K 房地产
6      主板  000008   神州高铁  1992-05-07   2,716,377,683   2,686,024,366   C 制造业
...   ...     ...    ...         ...             ...             ...     ...
2838  创业板  301577   美信科技  2024-01-24      44,260,000      11,095,149   C 制造业
2839  创业板  301578   辰奕智能  2023-12-28      48,000,000      11,378,776   C 制造业
2840  创业板  301588   美新科技  2024-03-13     118,867,754      22,582,500   C 制造业
2841  创业板  301589   诺瓦星云  2024-02-08      51,360,000       7,702,090   C 制造业
2842  创业板  301591   肯特股份  2024-02-28      84,120,000      19,943,633   C 制造业

[2771 rows x 7 columns]

In [15]:
symbol1 = stock_info_sh_name_code_df[['证券代码', '证券简称', '上市日期']].rename(columns={'证券代码': 'symbol', '证券简称': 'name', '上市日期': 'date'})
symbol1['market'] = 'sh'

In [16]:
symbol2 = stock_info_sz_name_code_df[['A股代码', 'A股简称', 'A股上市日期']].rename(columns={'A股代码': 'symbol', 'A股简称': 'name', 'A股上市日期': 'date'})
symbol2['market'] = 'sz'

In [17]:
symbols = pd.concat((symbol1, symbol2), axis=0)

In [18]:
symbols

      symbol  name        date market
0     600000  浦发银行  1999-11-10     sh
1     600004  白云机场  2003-04-28     sh
2     600006  东风汽车  1999-07-27     sh
3     600007  中国国贸  1999-03-12     sh
4     600008  首创环保  2000-04-27     sh
...      ...   ...         ...    ...
2838  301577  美信科技  2024-01-24     sz
2839  301578  辰奕智能  2023-12-28     sz
2840  301588  美新科技  2024-03-13     sz
2841  301589  诺瓦星云  2024-02-08     sz
2842  301591  肯特股份  2024-02-28     sz

[4429 rows x 4 columns]

In [19]:
stock_zh_a_spot_em_df = stock_zh_a_spot_em_df[stock_zh_a_spot_em_df['代码'].isin(symbols.symbol)]

In [20]:
stock_zh_a_spot_em_df

,序号,代码,名称,最新价,涨跌幅,涨跌额,成交量,成交额,振幅,最高,...,量比,换手率,市盈率-动态,市净率,总市值,流通市值,涨速,5分钟涨跌,60日涨跌幅,年初至今涨跌幅
0,1,603344,N星德胜,35.94,87.38,16.76,121005.0,4.375443e+08,20.02,38.36,...,NaN,25.39,35.31,3.72,6.991443e+09,1.712766e+09,-0.03,-0.03,87.38,87.38
1,2,301538,N骏鼎达,99.02,77.39,43.20,29572.0,2.929945e+08,22.36,108.00,...,NaN,31.18,28.28,3.50,3.960800e+09,9.390173e+08,-1.25,-2.09,77.39,77.39
2,3,300133,华策影视,7.68,20.00,1.28,1304735.0,9.631482e+08,12.34,7.68,...,12.24,8.01,33.46,2.08,1.460025e+10,1.250512e+10,0.00,0.00,13.78,30.83
3,4,301237,和顺科技,26.66,19.98,4.44,22136.0,5.686551e+07,18.41,26.66,...,34.48,5.67,79.75,1.48,2.132800e+09,1.040406e+09,0.00,0.00,-9.54,-12.50
5,6,300107,建新股份,6.00,16.05,0.83,592275.0,3.523234e+08,18.96,6.20,...,13.53,17.38,234.59,2.28,3.334611e+09,2.044698e+09,-3.23,-3.23,19.28,12.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5588,5589,000917,电广传媒,7.32,-4.44,-0.34,1181352.0,8.554654e+08,5.09,7.46,...,9.70,8.34,97.58,1.02,1.037651e+10,1.037440e+10,-0.27,0.00,15.09,33.58
5589,5590,301588,美新科技,31.03,-4.52,-1.47,33720.0,1.053616e+08,3.38,31.90,...,2.67,14.93,48.55,4.15,3.688466e+09,7.007350e+08,-0.06,-0.32,114.00,114.00
5591,5592,600373,中文传媒,15.91,-4.62,-0.77,153330.0,2.478085e+08,6.29,16.81,...,8.05,1.13,12.91,1.22,2.155906e+10,2.155906e+10,0.38,0.06,8.53,20.71
5595,5596,600381,青海春天,5.84,-4.89,-0.30,274951.0,1.589805e+08,2.28,5.86,...,8.12,4.68,-36.56,2.34,3.428435e+09,3.428435e+09,0.17,0.52,-24.74,-24.45
5599,5600,301246,宏源药业,19.72,-11.89,-2.66,115527.0,2.236669e+08,4.29,19.87,...,111.81,7.78,61.43,1.81,7.888134e+09,2.928449e+09,-0.55,-0.55,-23.57,-24.10

In [21]:
# stock_zcfz_em_df = ak.stock_zcfz_em(date='20230930') # date='20230930' 20230930 20231231

In [22]:
stock_zcfz_em_df1 = ak.stock_zcfz_em(date='20230331')
stock_zcfz_em_df2 = ak.stock_zcfz_em(date='20230630')
stock_zcfz_em_df3 = ak.stock_zcfz_em(date='20230930')
stock_zcfz_em_df4 = ak.stock_zcfz_em(date='20231231')

 27%|███████████▋                               | 3/11 [00:02<00:05,  1.48it/s]D:\Software\Python\Python39\lib\site-packages\akshare\stock_feature\stock_report_em.py:50: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  big_df = pd.concat([big_df, temp_df], ignore_index=True)
  9%|███▉                                       | 1/11 [00:01<00:12,  1.21s/it]D:\Software\Python\Python39\lib\site-packages\akshare\stock_feature\stock_report_em.py:50: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  big_df = pd.concat([big_df, temp_df], ignore_index=True)
  9%|███▉                                       | 1/11 [00:00<00:02,  4.35it/s]D:\Software\Python\Python39\lib\site-packages\akshare\stock_feature\stock_report_em.py:50: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  big_df = pd.concat([big_df, temp_df], ignore_index=True)

In [23]:
stock_zcfz_em_year_df = pd.concat((stock_zcfz_em_df1, stock_zcfz_em_df2, stock_zcfz_em_df3, stock_zcfz_em_df4), axis=0)

In [24]:
stock_zcfz_em_df = stock_zcfz_em_year_df[stock_zcfz_em_year_df.groupby('股票代码')['公告日期'].transform('max') == stock_zcfz_em_year_df['公告日期']]

In [25]:
debt_df = stock_zcfz_em_df[stock_zcfz_em_df['资产负债率'] < 30]

In [26]:
debt_df # [debt_df['股票代码'] == '300192']

,序号,股票代码,股票简称,资产-货币资金,资产-应收账款,资产-存货,资产-总资产,资产-总资产同比,负债-应付账款,负债-预收账款,负债-总负债,负债-总负债同比,资产负债率,股东权益合计,公告日期
5,6,300995,奇德新材,3.373476e+07,8.129302e+07,4.146487e+07,7.358095e+08,-0.153995,3.869812e+07,NaN,9.605450e+07,12.171485,13.054262,6.397550e+08,2024-01-18
8,9,300066,三川智慧,2.255217e+08,5.616092e+08,6.341123e+08,3.126105e+09,27.519777,1.557368e+08,NaN,6.720740e+08,176.497327,21.498767,2.454031e+09,2023-12-29
10,11,600868,梅雁吉祥,2.696449e+08,3.903776e+08,5.555867e+07,2.888185e+09,4.824277,1.406039e+08,NaN,3.866664e+08,14.215750,13.387869,2.501519e+09,2023-12-12
2638,2639,000616,*ST海投,3.021927e+06,3.108592e+06,1.138463e+07,5.390806e+09,-2.104927,7.731384e+07,NaN,9.187962e+08,71.187938,17.043763,4.472010e+09,2023-04-28
2,3,301587,中瑞股份,1.026712e+08,1.130894e+08,1.104713e+08,1.540390e+09,20.788054,1.664017e+08,NaN,3.787200e+08,31.224426,24.585984,1.161670e+09,2024-03-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,188,600219,南山铝业,2.638833e+10,3.229021e+09,6.271536e+09,6.881534e+10,6.317933,2.736212e+09,1.251509e+09,1.478724e+10,0.541618,21.488294,5.402810e+10,2024-02-29
189,190,002687,乔治白,8.234782e+08,3.888370e+08,2.450981e+08,2.236506e+09,13.278989,1.444893e+08,1.547521e+06,6.341323e+08,14.932217,28.353704,1.602374e+09,2024-02-29
192,193,300033,同花顺,8.169872e+09,5.408240e+07,NaN,9.844861e+09,9.053664,1.651384e+08,NaN,2.525513e+09,41.685729,25.653111,7.319348e+09,2024-02-27
197,198,001225,和泰机电,1.130818e+09,2.351314e+07,1.151346e+08,1.605475e+09,77.717359,6.769374e+07,NaN,1.577620e+08,-11.098958,9.826504,1.447713e+09,2024-02-22
200,201,002286,保龄宝,2.427358e+08,2.291103e+08,2.785824e+08,2.658892e+09,-11.551147,1.945588e+08,NaN,6.754065e+08,-32.580204,25.401800,1.983486e+09,2024-02-07

In [28]:
df = stock_zh_a_spot_em_df[(stock_zh_a_spot_em_df['总市值'] <= 4000000000) & (stock_zh_a_spot_em_df['代码'].isin(debt_df['股票代码'])) & (stock_zh_a_spot_em_df['换手率'] >= 10) & (stock_zh_a_spot_em_df['市盈率-动态'] <= 30) & (stock_zh_a_spot_em_df['市盈率-动态'] >= 0)]

In [31]:
df

,序号,代码,名称,最新价,涨跌幅,涨跌额,成交量,成交额,振幅,最高,...,量比,换手率,市盈率-动态,市净率,总市值,流通市值,涨速,5分钟涨跌,60日涨跌幅,年初至今涨跌幅
1,2,301538,N骏鼎达,99.02,77.39,43.2,29572.0,2.929945e+08,22.36,108.0,...,NaN,31.18,28.28,3.5,3.960800e+09,939017255.0,-1.25,-2.09,77.39,77.39

In [39]:
df[df['涨跌幅'].abs() >= 3]

,序号,代码,名称,最新价,涨跌幅,涨跌额,成交量,成交额,振幅,最高,...,量比,换手率,市盈率-动态,市净率,总市值,流通市值,涨速,5分钟涨跌,60日涨跌幅,年初至今涨跌幅
5313,5314,001216,华瓷股份,13.89,-3.07,-0.44,129699.0,181199842.9,3.56,14.30,...,0.82,20.60,17.67,2.25,3.498428e+09,874607463.0,0.00,0.00,7.67,6.44
5580,5581,605580,恒盛能源,10.80,-6.33,-0.73,181874.0,199207275.0,5.72,11.29,...,1.60,25.42,22.76,3.49,3.024000e+09,772783200.0,0.37,0.84,-9.40,-7.06

In [40]:
df

,序号,代码,名称,最新价,涨跌幅,涨跌额,成交量,成交额,振幅,最高,...,量比,换手率,市盈率-动态,市净率,总市值,流通市值,涨速,5分钟涨跌,60日涨跌幅,年初至今涨跌幅
786,787,301119,正强股份,21.92,1.15,0.25,29737.0,6.531089e+07,4.38,22.25,...,1.22,10.89,22.57,2.44,2.279680e+09,5.984160e+08,-0.05,0.32,-17.28,-15.30
815,816,301469,恒达新材,28.56,1.10,0.31,34159.0,9.780464e+07,3.89,29.17,...,1.21,15.55,27.30,1.90,2.555549e+09,6.271759e+08,-0.04,0.00,-16.54,-15.48
818,819,603231,索宝蛋白,19.36,1.10,0.21,56615.0,1.094598e+08,3.08,19.64,...,1.19,12.07,23.34,1.99,3.706648e+09,9.080904e+08,0.00,0.05,-31.97,-17.69
2950,2951,001219,青岛食品,16.77,-0.59,-0.10,79208.0,1.339187e+08,2.25,17.11,...,1.42,10.45,25.20,2.61,2.515290e+09,1.271418e+09,0.00,-0.06,-18.00,-27.25
3391,3392,301280,珠城科技,39.55,-0.88,-0.35,41707.0,1.657988e+08,4.29,40.82,...,0.78,15.81,26.97,2.28,3.864039e+09,1.043135e+09,0.00,-0.08,2.04,-3.72
3659,3660,001209,洪兴股份,15.29,-1.04,-0.16,42308.0,6.511808e+07,2.20,15.55,...,0.74,10.50,19.64,1.60,2.010982e+09,6.160014e+08,-0.07,0.00,-17.97,-14.63
4290,4291,300192,科德教育,11.13,-1.50,-0.17,229192.0,2.539717e+08,3.19,11.27,...,1.11,10.32,27.60,4.36,3.663365e+09,2.472444e+09,0.36,0.54,-3.05,12.77
4851,4852,301107,瑜欣电子,25.98,-2.04,-0.54,21939.0,5.750835e+07,2.53,26.63,...,1.10,10.46,25.62,2.07,1.906932e+09,5.450253e+08,0.08,-0.08,-16.78,-19.04
5123,5124,301550,斯菱股份,35.64,-2.52,-0.92,37649.0,1.353091e+08,2.76,36.65,...,0.82,13.69,26.26,2.46,3.920400e+09,9.801000e+08,-0.11,-0.14,-25.83,-23.16
5259,5260,301233,盛帮股份,37.75,-2.93,-1.14,23549.0,8.962237e+07,3.45,38.89,...,0.69,12.61,29.92,2.19,1.942992e+09,7.047378e+08,0.05,-0.29,-12.47,-15.02
5313,5314,001216,华瓷股份,13.89,-3.07,-0.44,129699.0,1.811998e+08,3.56,14.30,...,0.82,20.60,17.67,2.25,3.498428e+09,8.746075e+08,0.00,0.00,7.67,6.44
5580,5581,605580,恒盛能源,10.80,-6.33,-0.73,181874.0,1.992073e+08,5.72,11.29,...,1.60,25.42,22.76,3.49,3.024000e+09,7.727832e+08,0.37,0.84,-9.40,-7.06

In [43]:
df['代码'].to_frame().rename(columns={'代码': 'symbol'})

      symbol
786   301119
815   301469
818   603231
2950  001219
3391  301280
3659  001209
4290  300192
4851  301107
5123  301550
5259  301233
5313  001216
5580  605580

In [2]:
ltdxhq = LTdxHq()

In [3]:
dd = ltdxhq.get_k_data_daily('301119', start='2024-01-19')

d:\code\python\lutils3\lutils\stock\lpytdx.py:171: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df = df.assign(date=df[['year', 'month', 'day']].apply(lambda x: '{0}-{1:02d}-{2:02d}'.format(x[0], x[1], x[2]), axis=1))
d:\code\python\lutils3\lutils\stock\lpytdx.py:182: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  xdxr = xdxr.assign(date=xdxr[['year', 'month', 'day']].apply(lambda x: '{0}-{1:02d}-{2:02d}'.format(x[0], x[1], x[2]), axis=1))
d:\code\python\lutils3\lutils\stock\lpytdx.py:188: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.category = data.category.fillna(method='ffill')

In [8]:
dd['ma5'] = dd.ta.sma(5)

In [9]:
dd

             open  close   high    low     volume       amount     ma5
date
2024-01-19  24.20  23.35  24.20  23.35   664450.0   15683324.0     NaN
2024-01-22  23.31  22.00  23.58  21.70  1157660.0   26379624.0     NaN
2024-01-23  22.26  21.79  22.26  21.54  1034460.0   22527204.0     NaN
2024-01-24  21.75  21.88  22.30  20.97  1055524.0   22869414.0     NaN
2024-01-25  21.88  22.59  22.72  21.67   915050.0   20381938.0  22.322
2024-01-26  22.95  22.50  22.95  22.41   705400.0   15967891.0  22.152
2024-01-29  22.59  21.50  22.82  21.42   824940.0   17998832.0  22.052
2024-01-30  21.32  20.72  21.61  20.70   678938.0   14342125.0  21.838
2024-01-31  20.87  19.34  20.90  19.26  1304350.0   25917774.0  21.330
2024-02-01  19.28  19.10  19.36  18.24  1350490.0   25478094.0  20.632
2024-02-02  19.05  17.96  19.28  17.03  1640055.0   29633560.0  19.724
2024-02-05  17.71  14.95  17.73  14.40  2436060.0   37659384.0  18.414
2024-02-06  14.83  14.66  15.52  13.25  2752130.0   39206820.0  17.202
2024-02-07  14.64  13.57  14.73  13.25  3552764.0   49081920.0  16.048
2024-02-08  13.68  15.27  15.28  12.32  3964306.0   55891596.0  15.282
2024-02-19  15.90  16.08  16.36  15.50  3246091.0   51771132.0  14.906
2024-02-20  16.11  16.39  16.57  15.71  1932705.0   31403004.0  15.194
2024-02-21  16.28  17.19  17.99  16.11  2742820.0   47624996.0  15.700
2024-02-22  17.09  17.71  17.71  17.09  2043040.0   35580952.0  16.528
2024-02-23  17.86  18.44  18.62  17.52  2300820.0   41614580.0  17.162
2024-02-26  18.70  19.20  19.71  18.50  2829688.0   54153772.0  17.786
2024-02-27  19.37  23.04  23.04  19.05  5738001.0  127749984.0  19.116
2024-02-28  22.10  19.74  22.98  19.60  8138131.0  175349840.0  19.626
2024-02-29  19.14  21.20  22.15  19.03  6496068.0  133196912.0  20.324
2024-03-01  20.78  20.62  21.00  20.15  4159297.0   85661176.0  20.760
2024-03-04  20.32  20.11  20.63  19.36  3106350.0   61889172.0  20.942
2024-03-05  20.13  20.90  21.30  19.80  4427068.0   91953016.0  20.514
2024-03-06  20.10  20.64  20.78  20.04  2868340.0   58524008.0  20.694
2024-03-07  20.48  20.06  20.98  20.01  2873919.0   58891820.0  20.466
2024-03-08  19.87  20.00  20.19  19.56  1789964.0   35628460.0  20.342
2024-03-11  20.01  20.37  20.42  19.85  1733010.0   34909436.0  20.394
2024-03-12  20.53  21.03  21.20  20.40  2944586.0   61416164.0  20.420
2024-03-13  21.06  21.23  21.52  20.70  3068975.0   64814376.0  20.538
2024-03-14  21.15  20.83  21.29  20.40  1971209.0   41095344.0  20.692
2024-03-15  20.74  21.15  21.22  20.59  1696300.0   35554944.0  20.922
2024-03-18  21.18  21.67  21.80  21.18  2541740.0   54677900.0  21.182
2024-03-19  21.60  21.92  22.25  21.30  2973715.0   65310888.0  21.360

In [11]:
np.abs(dd.iloc[-1].close - dd.iloc[-1].ma5)

0.5600000000000023